### ISSUE TITLE
Error loading MPD Now Playing with user install

### ISSUE THREAD

**Issue by smartmic** [marcelh83/mpdnowplaying#1]
Hi there,
I am new to KDE and as such also to the Widget system.
**mpdnowplaying** looks great, so I tried to install it but did not succeed .

I could compile & `make install` as user locally, but when dragging the widget from Edit mode to the desktop, this error message appears:
```
file:///home/smartmic/.local/share/plasma/plasmoids/org.kde.plasma.mpdnowplaying/contents/ui/main.qml:31:1: module "org.kde.plasma.private.mpdnowplaying" is not installed
```

Compilation was successful but I had to use 
```
cmake -DCMAKE_INSTALL_PREFIX=/home/smartmic/.local ..
```
from the *build* directory because `qtpaths` was not helpful:
```
$ qtpaths --install-prefix
qtpaths: could not find a Qt installation of ''
```
Maybe this is part of the problem… or any other ideas what I did wrong?

My system:
Operating System: Void 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.6.0
Kernel Version: 6.6.31_1 (64-bit)
Graphics Platform: Wayland

**Comment by marcelh83** [comment]
I don't think installing widgets that use private plugins/modules locally will work. The plugin mpdnowplaying uses to communicate with mpd should be installed to the system-wide location for Plasma to find it. I'm not familiar with Void, but typically the install prefix will be /usr.
